### PR TITLE
Review for the (Tribute Page)

### PR DESCRIPTION
**Pull request by ZohalMirkhel**
I attempted to compose this document as closely resembling the sample one as I could. Primarily, the sample page features an image of Dr. Norman Borlaug alongside several biologists, which I slightly modified. Additionally, it provides details regarding the life of Dr. Norman Borlaug.

### CODE REVIEW

**Comment by ZohalMirkhel** [comment]
@ahzamir Please take a look at my third-week project as well. I'd greatly appreciate your feedback. Thank you!

**Comment by ZohalMirkhel** [comment]
@ahzamir sir, so I made a bit of a blunder. It seems I accidentally merged my feature branch into the development branch again, only realizing it after creating the pull request:( Do you think there's any way to solve this problem, or do I need to start all over again? Your guidance would be much appreciated!"

**Review by ahzamir — APPROVED** [review]
### Hi @ZohalMirkhel 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

ExcellentNiceGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Odin project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by ahzamir** [comment]
> @ahzamir sir, so I made a bit of a blunder. It seems I accidentally merged my feature branch into the development branch again, only realizing it after creating the pull request:( Do you think there's any way to solve this problem, or do I need to start all over again? Your guidance would be much appreciated!"

- No I don't see anything wrong here. You did not merge your branch. ✔️

**Pull request merged**
